//To check all available fonts, press command or control + click on the name of the font, and it will take you to the index.d.ts file where there is a list of available fonts

import { Roboto_Mono } from "next/font/google";
import "./globals.css";

const roboto = Roboto_Mono({ weight: "300", subsets: ["latin"] });

export const metadata = {
  title: "Slow Living Blog",
  description: "Generated by Natasha C creator",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
